//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBreak.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeBreak
    {
        public string Numero { get; set; }
        public bool Vegetariana { get; set; }
    
        public virtual Contrato Contrato { get; set; }
    }
}
